# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Darshil Kapadia
email: darshilkapadia9@gmail.com | 6692104620
description: darshilkapadia9@gmail.com | 6692104620
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  darshilpk3
linkedin_username: darshilpkapadia

# Build settings
markdown: kramdown
